### ISSUE TITLE
POCs, context, immediacy for each scoping convo

### ISSUE THREAD

**Issue by puja-b** [cityofaustin/knowledge-management-and-collaboration#49]

**Comment by ashleecoa** [comment]
@puja-b @sortizsh Could you add the point of contacts to each of these and a bit more detail on what was communicated to the department. Just need to make sure everything is covered by Ben/Marni when they email the folks. Thanks!

https://docs.google.com/spreadsheets/d/1xozBw7C0jS2HQ8VkzZvZCNS_BrJUCcOKtxfak8hbfsw/edit?usp=sharing
