### ISSUE TITLE
write blurb for ATD PIO newsletter

### ISSUE THREAD

**Issue by sortizsh** [cityofaustin/knowledge-management-and-collaboration#54]
write blurb for ATD PIO for their newsletter. provide blurb and photo to Vo, Mary <Mary.Vo@austintexas.gov>

should be general shareout of the research process and how this affects KM&C across city - Ben/Marni should review/approve correspondence

Next NL goes out on 7/2.

**Comment by ashleecoa** [comment]
Needs review https://docs.google.com/document/d/18v0H8TgjloFY0E1ka4ujpeIDmUPkzqgLm5-xzBCO9Uw/edit?usp=sharing
