### ISSUE TITLE
Close the loop with ARR, Code, and other departments 

### ISSUE THREAD

**Issue by ashleecoa** [cityofaustin/knowledge-management-and-collaboration#64]
We need to follow up with departments that we've previously contacted to let them know future direction of this project. 

Contact list: https://docs.google.com/spreadsheets/d/1xozBw7C0jS2HQ8VkzZvZCNS_BrJUCcOKtxfak8hbfsw/edit#gid=0

**Comment by sortizsh** [comment]
received an email from Code today asking for follow up.

**Comment by ashleecoa** [comment]
@sortizsh Update:

Marni closed loop with Vicki Pudgen of Code
Marni reach out to Emlea, but haven't heard back
Ben is reaching out to to Capital Contracting
I'll be sending out an email to the rest of the departments
