### ISSUE TITLE
Create EMS facilitation decks and guides for all 4 sessions

### ISSUE THREAD

**Issue by ashleecoa** [cityofaustin/knowledge-management-and-collaboration#72]

**Comment by puja-b** [comment]
https://drive.google.com/open?id=1iL8R5z248cvNHSFoWu1d6jE08g1RNnuiXHv8xMaJIP4
https://drive.google.com/open?id=12pLaq2FRPV0QU-6NTQU_egMuIouHdQdajKX6JOL7sYQ
https://drive.google.com/open?id=1AQM8pHcRoSOfsmCt_aCtVuG15IwOdGs99QbfjlCxtCs
