### ISSUE TITLE
Read through reading materials sent from Farah

### ISSUE THREAD

**Issue by ashleecoa** [cityofaustin/knowledge-management-and-collaboration#78]

**Comment by sortizsh** [comment]
May 22, 2018 Work Session Presentation

Here is a copy of the presentation:

http://www.austintexas.gov/edims/document.cfm?id=298958

 

Here is a video presentation:

http://austintx.swagit.com/play/05222018-790

 

Preliminary Oversight Report from June 26, 2018 Work Session

http://www.austintexas.gov/edims/document.cfm?id=301093

 

Auditor’s Office Report (Video)

Item 3 – Follow Up on the APD Handling of Complaints Audit

http://austintx.swagit.com/play/06252018-875

 

Report:

http://www.austintexas.gov/sites/default/files/files/Auditor/Audit_Reports/APD_Complaints_Follow-Up_June_2018__v1_.pdf

 

Item 4 – Effectiveness of Citizen Police Oversight Audit (Video)

http://austintx.swagit.com/play/06252018-875

Report:

http://www.austintexas.gov/sites/default/files/files/Auditor/Audit_Reports/Effectiveness_of_Citizen_Police_Oversight_June_2018.pdf

 

OPM Annual Reports

http://www.austintexas.gov/department/annual-police-monitor-reports
